### ISSUE TITLE
SBT compatibility error

### ISSUE THREAD

**Issue by ASchmidt84** [geirolz/advxml#248] opened 2021-07-30 11:58 UTC
Try to import with this 
"com.github.geirolz" %% "advxml-core" % "2.4.0"

using scala 2.13.6 getting all the time a resolving error:

```
[error] (gui / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.0.1 (early-semver) is selected over {1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.0.6}
[error] 	    +- com.github.geirolz:advxml-core_2.12:2.4.0          (depends on 2.0.1)
[error] 	    +- org.scala-lang:scala-compiler:2.12.14              (depends on 1.0.6)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error] 	    +- com.typesafe.play:play-ws-standalone-xml_2.12:2.1.3 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-scaladsl-cluster_2.12:1.6.5 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-persistence-jdbc-core_2.12:1.6.5 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-persistence-core_2.12:1.6.5 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-cluster-core_2.12:1.6.5  (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-api_2.12:1.6.5           (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-akka-management-core_2.12:1.6.5 (depends on 1.2.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] (gui / ssExtractDependencies) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.0.1 (early-semver) is selected over {1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.0.6}
[error] 	    +- com.github.geirolz:advxml-core_2.12:2.4.0          (depends on 2.0.1)
[error] 	    +- org.scala-lang:scala-compiler:2.12.14              (depends on 1.0.6)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error] 	    +- com.typesafe.play:play-ws-standalone-xml_2.12:2.1.3 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-scaladsl-cluster_2.12:1.6.5 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-persistence-jdbc-core_2.12:1.6.5 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-persistence-core_2.12:1.6.5 (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-cluster-core_2.12:1.6.5  (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-api_2.12:1.6.5           (depends on 1.2.0)
[error] 	    +- com.lightbend.lagom:lagom-akka-management-core_2.12:1.6.5 (depends on 1.2.0)
```
do you have any idea to solve it?

Thank you

**Comment by geirolz** [comment] 2021-07-30 15:09
Hi, @ASchmidt84! Here seems you are using Scala 2.12 not 2.13. Anyway, the problem is not related to SBT but to all other libraries that depend on a different version of scala-xml module. 

Try to use Scala 2.13 and check if there are some updates for the libraries listed

**Comment by geirolz** [comment] 2021-08-12 10:42
@ASchmidt84 did you resolve? Can we close this issue?

**Closed** 2021-08-25 10:56 UTC
Labels: help wanted
